// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVSlk3_t59dXdJc0GAiObTCrFRF6rO-9M',
    appId: '1:993627818585:web:6e4bc3c897eda9f21e3f48',
    messagingSenderId: '993627818585',
    projectId: 'ecomm-569af',
    authDomain: 'ecomm-569af.firebaseapp.com',
    storageBucket: 'ecomm-569af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ34IQJiTYx7CYSmRNOd9UfK_rUXt42Fg',
    appId: '1:993627818585:android:556e54dc74b7f11e1e3f48',
    messagingSenderId: '993627818585',
    projectId: 'ecomm-569af',
    storageBucket: 'ecomm-569af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGuyq3UoCRjNXJvyVvc4sCVEREpIy90I',
    appId: '1:993627818585:ios:2f520ee0b3e021351e3f48',
    messagingSenderId: '993627818585',
    projectId: 'ecomm-569af',
    storageBucket: 'ecomm-569af.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );
}
